data:
    type: "LOLv2"
    patch_size: 256
    channels: 3
    num_workers: 8
    gt_dir: "Test/Normal"
    data_dir: "../data/LOLv2/Real_captured"
    conditional: True

model:
    model_type: "SDTL" # DDPM or Control or Adapter, DiT, SDTL
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200 # 扩散模型需要执行的步数；

training:
    batch_size: 8
    n_epochs: 500
    save_epoch: 100
    vis_sample_epoch: 50

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0005
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.90 # 目前90效果最好

